# Generated by Django 4.1 on 2022-08-10 19:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("origin", models.CharField(max_length=300)),
                ("destination", models.CharField(max_length=300)),
                ("start_date", models.DateField(default=datetime.datetime.now)),
                ("end_date", models.DateField(default=datetime.datetime.now)),
                ("creation_date", models.DateField(default=datetime.datetime.now)),
                ("last_update", models.DateField(default=datetime.datetime.now)),
                ("public", models.BooleanField(default=False, verbose_name="Public")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="last_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.TextField(max_length=20)),
                ("value", models.TextField(max_length=20)),
                ("create_date", models.DateField(default=datetime.datetime.now)),
                ("update_date", models.DateField(default=datetime.datetime.now)),
                (
                    "create_setting_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="create_setting_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "update_setting_member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="update_setting_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=1024)),
                ("gmaps_id", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=20)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=20)),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=20)),
                ("retrieval_date", models.DateField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-retrieval_date"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("message_body", models.TextField(max_length=1024)),
                ("create_date", models.DateField(default=datetime.datetime.now)),
                (
                    "create_message_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("join_date", models.DateField(default=datetime.datetime.now)),
                ("name", models.CharField(max_length=20)),
                ("update_date", models.DateField(default=datetime.datetime.now)),
                (
                    "create_member_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="create_member_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_in_trip",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.trip",
                    ),
                ),
                (
                    "update_member_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="update_member_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checklist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.TextField(max_length=20)),
                ("remark", models.TextField(max_length=1024)),
                ("create_date", models.DateField(default=datetime.datetime.now)),
                ("update_date", models.DateField(default=datetime.datetime.now)),
                (
                    "create_checklist_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="create_checklist_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.trip",
                    ),
                ),
                (
                    "update_checklist_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="update_checklist_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_in_charge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_in_charge",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.TextField(max_length=20)),
                ("price", models.IntegerField(blank=True, default=0)),
                ("remark", models.TextField(max_length=1024)),
                ("create_date", models.DateField(default=datetime.datetime.now)),
                ("update_date", models.DateField(default=datetime.datetime.now)),
                (
                    "create_budget_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="create_budget_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.trip",
                    ),
                ),
                (
                    "update_budget_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="update_budget_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
