# Generated by Django 4.1 on 2022-08-08 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=1024)),
                ("place_id", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=20)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=20)),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=20)),
                ("retrieval_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-retrieval_date"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                (
                    "destination_latitude",
                    models.DecimalField(decimal_places=15, max_digits=20),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(decimal_places=15, max_digits=20),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("last_update", models.DateField(auto_now_add=True)),
                ("public", models.BooleanField(default=False, verbose_name="Public")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="last_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
    ]
